//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EmidsIHStatModel", "FK__UserData__GroupI__4F7CD00D", "Group", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.Group), "UserData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.UserData), true)]
[assembly: EdmRelationshipAttribute("EmidsIHStatModel", "FK__UserData__RoleID__4E88ABD4", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.Role), "UserData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.UserData), true)]
[assembly: EdmRelationshipAttribute("EmidsIHStatModel", "FK__StatusRep__UserI__571DF1D5", "UserData", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.UserData), "StatusReport", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.StatusReport), true)]

#endregion

namespace DataAccessLayer.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EmidsIHStatEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EmidsIHStatEntities object using the connection string found in the 'EmidsIHStatEntities' section of the application configuration file.
        /// </summary>
        public EmidsIHStatEntities() : base("name=EmidsIHStatEntities", "EmidsIHStatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmidsIHStatEntities object.
        /// </summary>
        public EmidsIHStatEntities(string connectionString) : base(connectionString, "EmidsIHStatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmidsIHStatEntities object.
        /// </summary>
        public EmidsIHStatEntities(EntityConnection connection) : base(connection, "EmidsIHStatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Group> Groups
        {
            get
            {
                if ((_Groups == null))
                {
                    _Groups = base.CreateObjectSet<Group>("Groups");
                }
                return _Groups;
            }
        }
        private ObjectSet<Group> _Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StatusReport> StatusReports
        {
            get
            {
                if ((_StatusReports == null))
                {
                    _StatusReports = base.CreateObjectSet<StatusReport>("StatusReports");
                }
                return _StatusReports;
            }
        }
        private ObjectSet<StatusReport> _StatusReports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserData> UserDatas
        {
            get
            {
                if ((_UserDatas == null))
                {
                    _UserDatas = base.CreateObjectSet<UserData>("UserDatas");
                }
                return _UserDatas;
            }
        }
        private ObjectSet<UserData> _UserDatas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroups(Group group)
        {
            base.AddObject("Groups", group);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StatusReports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatusReports(StatusReport statusReport)
        {
            base.AddObject("StatusReports", statusReport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserDatas(UserData userData)
        {
            base.AddObject("UserDatas", userData);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="username">No Metadata Documentation available.</param>
        /// <param name="uPassword">No Metadata Documentation available.</param>
        /// <param name="retUserID">No Metadata Documentation available.</param>
        /// <param name="retName">No Metadata Documentation available.</param>
        /// <param name="retGroupID">No Metadata Documentation available.</param>
        /// <param name="retRoleId">No Metadata Documentation available.</param>
        public int AuthenticateUser(global::System.String username, global::System.String uPassword, ObjectParameter retUserID, ObjectParameter retName, ObjectParameter retGroupID, ObjectParameter retRoleId)
        {
            ObjectParameter usernameParameter;
            if (username != null)
            {
                usernameParameter = new ObjectParameter("Username", username);
            }
            else
            {
                usernameParameter = new ObjectParameter("Username", typeof(global::System.String));
            }
    
            ObjectParameter uPasswordParameter;
            if (uPassword != null)
            {
                uPasswordParameter = new ObjectParameter("UPassword", uPassword);
            }
            else
            {
                uPasswordParameter = new ObjectParameter("UPassword", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("AuthenticateUser", usernameParameter, uPasswordParameter, retUserID, retName, retGroupID, retRoleId);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="uID">No Metadata Documentation available.</param>
        public ObjectResult<StatusReport> GetCurrentRecord(Nullable<global::System.Int32> uID)
        {
            ObjectParameter uIDParameter;
            if (uID.HasValue)
            {
                uIDParameter = new ObjectParameter("UID", uID);
            }
            else
            {
                uIDParameter = new ObjectParameter("UID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<StatusReport>("GetCurrentRecord", uIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="uID">No Metadata Documentation available.</param>
        public ObjectResult<StatusReport> GetCurrentRecord(Nullable<global::System.Int32> uID, MergeOption mergeOption)
        {
            ObjectParameter uIDParameter;
            if (uID.HasValue)
            {
                uIDParameter = new ObjectParameter("UID", uID);
            }
            else
            {
                uIDParameter = new ObjectParameter("UID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<StatusReport>("GetCurrentRecord", mergeOption, uIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="gID">No Metadata Documentation available.</param>
        public ObjectResult<GetCurrentTeamRecord_Result> GetCurrentTeamRecord(Nullable<global::System.Int32> gID)
        {
            ObjectParameter gIDParameter;
            if (gID.HasValue)
            {
                gIDParameter = new ObjectParameter("GID", gID);
            }
            else
            {
                gIDParameter = new ObjectParameter("GID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<GetCurrentTeamRecord_Result>("GetCurrentTeamRecord", gIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="uid">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public int ChangePassword(Nullable<global::System.Int32> uid, global::System.String password)
        {
            ObjectParameter uidParameter;
            if (uid.HasValue)
            {
                uidParameter = new ObjectParameter("uid", uid);
            }
            else
            {
                uidParameter = new ObjectParameter("uid", typeof(global::System.Int32));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("ChangePassword", uidParameter, passwordParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmidsIHStatModel", Name="Group")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Group : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Group object.
        /// </summary>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        /// <param name="groupName">Initial value of the GroupName property.</param>
        public static Group CreateGroup(global::System.Int32 groupID, global::System.String groupName)
        {
            Group group = new Group();
            group.GroupID = groupID;
            group.GroupName = groupName;
            return group;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmidsIHStatModel", "FK__UserData__GroupI__4F7CD00D", "UserData")]
        public EntityCollection<UserData> UserDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserData>("EmidsIHStatModel.FK__UserData__GroupI__4F7CD00D", "UserData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserData>("EmidsIHStatModel.FK__UserData__GroupI__4F7CD00D", "UserData", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmidsIHStatModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        /// <param name="roleName">Initial value of the RoleName property.</param>
        public static Role CreateRole(global::System.Int32 roleID, global::System.String roleName)
        {
            Role role = new Role();
            role.RoleID = roleID;
            role.RoleName = roleName;
            return role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmidsIHStatModel", "FK__UserData__RoleID__4E88ABD4", "UserData")]
        public EntityCollection<UserData> UserDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserData>("EmidsIHStatModel.FK__UserData__RoleID__4E88ABD4", "UserData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserData>("EmidsIHStatModel.FK__UserData__RoleID__4E88ABD4", "UserData", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmidsIHStatModel", Name="StatusReport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatusReport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StatusReport object.
        /// </summary>
        /// <param name="serialNumber">Initial value of the SerialNumber property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="jiraID">Initial value of the JiraID property.</param>
        /// <param name="employeeName">Initial value of the EmployeeName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="percentComplete">Initial value of the PercentComplete property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        public static StatusReport CreateStatusReport(global::System.Int32 serialNumber, global::System.Int32 userID, global::System.String jiraID, global::System.String employeeName, global::System.String description, global::System.Int32 percentComplete, global::System.DateTime timestamp)
        {
            StatusReport statusReport = new StatusReport();
            statusReport.SerialNumber = serialNumber;
            statusReport.UserID = userID;
            statusReport.JiraID = jiraID;
            statusReport.EmployeeName = employeeName;
            statusReport.Description = description;
            statusReport.PercentComplete = percentComplete;
            statusReport.Timestamp = timestamp;
            return statusReport;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SerialNumber
        {
            get
            {
                return _SerialNumber;
            }
            set
            {
                if (_SerialNumber != value)
                {
                    OnSerialNumberChanging(value);
                    ReportPropertyChanging("SerialNumber");
                    _SerialNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SerialNumber");
                    OnSerialNumberChanged();
                }
            }
        }
        private global::System.Int32 _SerialNumber;
        partial void OnSerialNumberChanging(global::System.Int32 value);
        partial void OnSerialNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JiraID
        {
            get
            {
                return _JiraID;
            }
            set
            {
                OnJiraIDChanging(value);
                ReportPropertyChanging("JiraID");
                _JiraID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JiraID");
                OnJiraIDChanged();
            }
        }
        private global::System.String _JiraID;
        partial void OnJiraIDChanging(global::System.String value);
        partial void OnJiraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeName
        {
            get
            {
                return _EmployeeName;
            }
            set
            {
                OnEmployeeNameChanging(value);
                ReportPropertyChanging("EmployeeName");
                _EmployeeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmployeeName");
                OnEmployeeNameChanged();
            }
        }
        private global::System.String _EmployeeName;
        partial void OnEmployeeNameChanging(global::System.String value);
        partial void OnEmployeeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PercentComplete
        {
            get
            {
                return _PercentComplete;
            }
            set
            {
                OnPercentCompleteChanging(value);
                ReportPropertyChanging("PercentComplete");
                _PercentComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PercentComplete");
                OnPercentCompleteChanged();
            }
        }
        private global::System.Int32 _PercentComplete;
        partial void OnPercentCompleteChanging(global::System.Int32 value);
        partial void OnPercentCompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlanEndDate
        {
            get
            {
                return _PlanEndDate;
            }
            set
            {
                OnPlanEndDateChanging(value);
                ReportPropertyChanging("PlanEndDate");
                _PlanEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlanEndDate");
                OnPlanEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlanEndDate;
        partial void OnPlanEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPlanEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmidsIHStatModel", "FK__StatusRep__UserI__571DF1D5", "UserData")]
        public UserData UserData
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserData>("EmidsIHStatModel.FK__StatusRep__UserI__571DF1D5", "UserData").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserData>("EmidsIHStatModel.FK__StatusRep__UserI__571DF1D5", "UserData").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserData> UserDataReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserData>("EmidsIHStatModel.FK__StatusRep__UserI__571DF1D5", "UserData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserData>("EmidsIHStatModel.FK__StatusRep__UserI__571DF1D5", "UserData", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmidsIHStatModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmidsIHStatModel", Name="UserData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserData object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="empName">Initial value of the EmpName property.</param>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        public static UserData CreateUserData(global::System.Int32 userID, global::System.String userName, global::System.String password, global::System.String empName, global::System.Int32 groupID, global::System.Int32 roleID)
        {
            UserData userData = new UserData();
            userData.UserID = userID;
            userData.UserName = userName;
            userData.Password = password;
            userData.EmpName = empName;
            userData.GroupID = groupID;
            userData.RoleID = roleID;
            return userData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpName
        {
            get
            {
                return _EmpName;
            }
            set
            {
                OnEmpNameChanging(value);
                ReportPropertyChanging("EmpName");
                _EmpName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpName");
                OnEmpNameChanged();
            }
        }
        private global::System.String _EmpName;
        partial void OnEmpNameChanging(global::System.String value);
        partial void OnEmpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmidsIHStatModel", "FK__UserData__GroupI__4F7CD00D", "Group")]
        public Group Group
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("EmidsIHStatModel.FK__UserData__GroupI__4F7CD00D", "Group").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("EmidsIHStatModel.FK__UserData__GroupI__4F7CD00D", "Group").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Group> GroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("EmidsIHStatModel.FK__UserData__GroupI__4F7CD00D", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Group>("EmidsIHStatModel.FK__UserData__GroupI__4F7CD00D", "Group", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmidsIHStatModel", "FK__UserData__RoleID__4E88ABD4", "Role")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("EmidsIHStatModel.FK__UserData__RoleID__4E88ABD4", "Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("EmidsIHStatModel.FK__UserData__RoleID__4E88ABD4", "Role").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("EmidsIHStatModel.FK__UserData__RoleID__4E88ABD4", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("EmidsIHStatModel.FK__UserData__RoleID__4E88ABD4", "Role", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmidsIHStatModel", "FK__StatusRep__UserI__571DF1D5", "StatusReport")]
        public EntityCollection<StatusReport> StatusReports
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StatusReport>("EmidsIHStatModel.FK__StatusRep__UserI__571DF1D5", "StatusReport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StatusReport>("EmidsIHStatModel.FK__StatusRep__UserI__571DF1D5", "StatusReport", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EmidsIHStatModel", Name="GetCurrentTeamRecord_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetCurrentTeamRecord_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetCurrentTeamRecord_Result object.
        /// </summary>
        /// <param name="jiraID">Initial value of the JiraID property.</param>
        /// <param name="empName">Initial value of the EmpName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="percentComplete">Initial value of the PercentComplete property.</param>
        public static GetCurrentTeamRecord_Result CreateGetCurrentTeamRecord_Result(global::System.String jiraID, global::System.String empName, global::System.String description, global::System.Int32 percentComplete)
        {
            GetCurrentTeamRecord_Result getCurrentTeamRecord_Result = new GetCurrentTeamRecord_Result();
            getCurrentTeamRecord_Result.JiraID = jiraID;
            getCurrentTeamRecord_Result.EmpName = empName;
            getCurrentTeamRecord_Result.Description = description;
            getCurrentTeamRecord_Result.PercentComplete = percentComplete;
            return getCurrentTeamRecord_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JiraID
        {
            get
            {
                return _JiraID;
            }
            set
            {
                OnJiraIDChanging(value);
                ReportPropertyChanging("JiraID");
                _JiraID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JiraID");
                OnJiraIDChanged();
            }
        }
        private global::System.String _JiraID;
        partial void OnJiraIDChanging(global::System.String value);
        partial void OnJiraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpName
        {
            get
            {
                return _EmpName;
            }
            set
            {
                OnEmpNameChanging(value);
                ReportPropertyChanging("EmpName");
                _EmpName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpName");
                OnEmpNameChanged();
            }
        }
        private global::System.String _EmpName;
        partial void OnEmpNameChanging(global::System.String value);
        partial void OnEmpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PercentComplete
        {
            get
            {
                return _PercentComplete;
            }
            set
            {
                OnPercentCompleteChanging(value);
                ReportPropertyChanging("PercentComplete");
                _PercentComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PercentComplete");
                OnPercentCompleteChanged();
            }
        }
        private global::System.Int32 _PercentComplete;
        partial void OnPercentCompleteChanging(global::System.Int32 value);
        partial void OnPercentCompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlanEndDate
        {
            get
            {
                return _PlanEndDate;
            }
            set
            {
                OnPlanEndDateChanging(value);
                ReportPropertyChanging("PlanEndDate");
                _PlanEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlanEndDate");
                OnPlanEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlanEndDate;
        partial void OnPlanEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPlanEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion

    }

    #endregion

    
}
